seed: 0
lr: 1e-6
critic_lr: 1e-6
run_dir: ./run_results/
log_interval: 1
use_recurrent_policy: true
use_valuenorm: true
use_adv_normalize: true
wandb_entity: "openrl-lab"
ppo_epoch: 5
episode_length: 16
num_mini_batch: 2
use_share_model: true
# use_amp: true
hidden_size: 1
data_chunk_length: 1

model_path: /home/chenwenze/data_server/huggingface/models/rajkumarrrk/gpt2-fine-tuned-on-daily-dialog
env:
  args: {
    'tokenizer_path': '/home/chenwenze/data_server/huggingface/models/gpt2',
    'data_path': '/home/chenwenze/data_server/huggingface/datasets/daily_dialog',
  }
vec_info_class:
  id: "NLPVecInfo"
reward_class: 
  id: "NLPReward"
  args: { 
    "intent_model": "/home/chenwenze/data_server/huggingface/models/rajkumarrrk/roberta-daily-dialog-intent-classifier",
    "ref_model": "/home/chenwenze/data_server/huggingface/models/rajkumarrrk/gpt2-fine-tuned-on-daily-dialog",
  }
    