seed: 0
lr: 1e-6
critic_lr: 1e-6
run_dir: ./run_results/
log_interval: 1
use_recurrent_policy: true
use_valuenorm: true
use_adv_normalize: true
wandb_entity: "openrl-lab"
ppo_epoch: 5
episode_length: 128
num_mini_batch: 20
use_share_model: true
hidden_size: 1
data_chunk_length: 1
local_rank: -1
use_deepspeed: true

model_path: /home/chenwenze/data_server/huggingface/models/facebook/opt-125m
env:
  args: {
    'tokenizer_path': '/home/chenwenze/data_server/huggingface/models/facebook/opt-125m',
    'data_path': 'daily_dialog',
  }
vec_info_class:
  id: "NLPVecInfo"
reward_class: 
  id: "NLPReward"
  args: { 
    "intent_model": "/home/chenwenze/data_server/huggingface/models/rajkumarrrk/roberta-daily-dialog-intent-classifier",
    "ref_model": "/home/chenwenze/data_server/huggingface/models/facebook/opt-125m",
  }
    