seed: 0
lr: 1e-7
critic_lr: 1e-7
run_dir: ./run_results/
log_interval: 1
use_valuenorm: true
use_adv_normalize: true
wandb_entity: "openrl-lab"
ppo_epoch: 5
episode_length: 128
num_mini_batch: 20

hidden_size: 1

model_path: /home/chenwenze/data_server/huggingface/models/facebook/opt-125m
env:
  args: {
    'tokenizer_path': '/home/chenwenze/data_server/huggingface/models/facebook/opt-125m',
    'data_path': '/home/chenwenze/data_server/huggingface/datasets/daily_dialog',
  }
vec_info_class:
  id: "NLPVecInfo"
reward_class: 
  id: "NLPReward"
  args: {
    "ref_model": "/home/chenwenze/data_server/huggingface/models/facebook/opt-125m",
    "intent_model": "/home/chenwenze/data_server/huggingface/models/rajkumarrrk/roberta-daily-dialog-intent-classifier",
  }
    