seed: 0
lr: 2e-7
critic_lr: 2e-7
run_dir: ./run_results/
log_interval: 1
use_valuenorm: true
use_adv_normalize: true
wandb_entity: "openrl-lab"
ppo_epoch: 5
episode_length: 112
num_mini_batch: 20
use_share_model: true

hidden_size: 1
use_deepspeed: true
use_fp16: true

model_path: rajkumarrrk/gpt2-fine-tuned-on-daily-dialog
env:
  args: {
    'tokenizer_path': 'gpt2',
    'data_path': 'daily_dialog',
  }
vec_info_class:
  id: "NLPVecInfo"
reward_class: 
  id: "NLPReward"
  args: { 
    "intent_model": "rajkumarrrk/roberta-daily-dialog-intent-classifier",
    "ref_model": "rajkumarrrk/gpt2-fine-tuned-on-daily-dialog",
    "use_deepspeed": true,
  }
    