name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve OpenRL
title: "[Bug]: bug title"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior. Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.
      value: |
        ```python
        from openrl import ...

        ```

  - type: textarea
    id: traceback
    attributes:
      label: Relevant log output / Error message
      description: Please copy and paste any relevant log output / error message.
      placeholder: "Traceback (most recent call last): File ..."
      render: shell

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        Describe the characteristic of your environment:
         * Describe how the library was installed (pip, conda, source, ...)
         * GPU models and configuration
         * Python version
         * PyTorch version
         * Versions of any other relevant libraries

        You can use `openrl --system_info` to get relevant packages info:
        ```sh
        openrl --system_info
        ```
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked that there is no similar [issues](https://github.com/OpenRL-Lab/openrl/issues) in the repo
          required: true
        - label: I have read the [documentation](https://openrl-docs.readthedocs.io/)
          required: true
        - label: I have provided a minimal working example to reproduce the bug
          required: true
        - label: I have version numbers, operating system and environment, where applicable
          required: true

