name: "\U0001F4DA Documentation"
description: Report an issue related to OpenRL documentation
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: 📚 Documentation
      description: A clear and concise description of what should be improved in the documentation.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked that there is no similar [issues](https://github.com/OpenRL-Lab/openrl/issues) in the repo
          required: true
        - label: I have read the [documentation](https://openrl-docs.readthedocs.io/)
          required: true
