seed: 0
lr: 1e-2
critic_lr: 1e-2
episode_length: 128
ppo_epoch: 4
num_mini_batch: 4
gae_lambda: 0.8
run_dir: ./run_results/
experiment_name: train_crafter
log_interval: 1
use_recurrent_policy: true
use_joint_action_loss: false
use_valuenorm: true
use_adv_normalize: true
wandb_entity: cwz19

reward_class: 
  id: "CrafterReward"
  args: {
    "api_key": "EMPTY", #"isQQQqPJUUSWXvz4NqG36Q6v5pxdPTkG",
    "api_base": "http://localhost:11017/v1", # "https://azure-openai-api.shenmishajing.workers.dev/v1", 
    "model": "meta-llama/Llama-2-70b-chat-hf", #"berkeley-nest/Starling-LM-7B-alpha" #"gpt-4-32k",
    "base_model": "/zfsauton2/home/wentsec/openrl/examples/crafter/crafter_agent-50M"
  }
vec_info_class:
  id: "CrafterVecInfo"