seed: 0
lr: 7e-4
critic_lr: 7e-4
episode_length: 512
<<<<<<< HEAD
ppo_epoch: 5
=======
ppo_epochs: 5
>>>>>>> 2993d08ceecdb4fadc190fad513bc7c08db70e1d
data_chunk_length: 8
num_mini_batch: 8
run_dir: ./run_results/
experiment_name: train_crafter
log_interval: 10
use_recurrent_policy: true
use_joint_action_loss: false
use_valuenorm: true
use_adv_normalize: true
wandb_entity: cwz19
