seed: 0
lr: 2e-4
critic_lr: 2e-4
episode_length: 512
ppo_epoch: 4
num_mini_batch: 8
gae_lambda: 0.8
entropy_coef: 0.01
run_dir: ./run_results/
experiment_name: train_crafter
log_interval: 10
use_recurrent_policy: true
use_joint_action_loss: false
use_valuenorm: true
use_adv_normalize: true
wandb_entity: cwz19
