seed: 0
lr: 2e-4
critic_lr: 2e-4
episode_length: 512
ppo_epoch: 5
data_chunk_length: 2
num_mini_batch: 8
gae_lambda: 0.8
entropy_coef: 0.03
run_dir: ./run_results/
experiment_name: train_crafter
use_recurrent_policy: true
use_joint_action_loss: false
use_valuenorm: true
use_adv_normalize: true

log_interval: 10
wandb_entity: cwz19
vec_info_class:
  id: "EPS_RewardInfo"